name: Shell Commands

on: [push]

jobs:
  run-sell-command:
   runs-on: ubuntu-latest
   steps:
     - name: echo a string
       run: echo "Hellow world"
     - name: multiline script
       run: |
         node -v
         npm -v

#cuanto daria por contarles nuestro amor
#blablacar